---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: descheduler
    namespace: descheduler
spec:
    url: https://kubernetes-sigs.github.io/descheduler/
    interval: 10m
