---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: kube-system
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    hostname: rancher.local.danielvignoles.com
    bootstrapPassword: ${SECRET_RANCHER_BOOTSTRAP_PASSWORD}
    tls: external
