---
name: podinfo

networks:
  proxy:
    external: true

services:
  podinfo:
    image: docker.io/stefanprodan/podinfo:6.7.1
    pull_policy: always
    container_name: podinfo
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.podinfo.entrypoints=https"
      - "traefik.http.routers.podinfo.rule=Host(`podinfo.home.irishlab.io`)"
      - "traefik.http.routers.podinfo.tls=true"
      - "traefik.http.services.podinfo.loadbalancer.server.port=9898"
    networks:
      - proxy
