---
- name: Install
  block:
    - name: Upgrade system
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: Install packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - dnsutils
        - ffmpeg
    - name: Set timezone
      community.general.timezone:
        name: "{{ os_timezone | default('Europe/Stockholm') }}"
    - name: Set hostname to inventory hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      when:
        - ansible_hostname != inventory_hostname
  rescue:
    - name: Mount read-only
      ansible.builtin.command: /usr/local/bin/ro
      changed_when: false

- name: Configure
  notify: Restart kvmd
  block:
    - name: Create kvmd override configuration
      ansible.builtin.template:
        src: override.yaml.j2
        dest: /etc/kvmd/override.yaml
        mode: "0644"
    - name: Load custom EDID file
      ansible.builtin.template:
        src: tc358743-edid.hex.j2
        dest: /etc/kvmd/tc358743-edid.hex
        mode: "0644"
  rescue:
    - name: Mount read-only
      ansible.builtin.command: /usr/local/bin/ro
      changed_when: false
