---
volumes:
  overseerr:
    name: overseerr
    external: false

services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
