---
version: '3.7'

networks:
  lan:
    name: lan
    external: false

services:
  traefik:
    image: docker.io/traefik:latest
    container_name: traefik
    networks:
      - lan
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: wget --quiet --tries=1 --spider http://ping.127.0.0.1.nip.io/ping || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s
    command:
      - "--global.sendAnonymousUsage=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
    restart: unless-stopped
