---
name: traefik
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  traefik:
    image: docker.io/traefik:v3.0
    container_name: traefik
    networks:
      - frontend
      - backend
    ports:
      - mode: ingress
        target: 80
        published: "88"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
      - mode: ingress
        target: 8080
        published: "8088"
        protocol: tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    restart: unless-stopped
