---
- name: Setup additional repo
  ansible.builtin.include_tasks: repo.yml
- name: Update servers
  ansible.builtin.include_tasks: update.yml
- name: Install packages
  ansible.builtin.include_tasks: packages.yml
- name: Configure ufw
  ansible.builtin.include_tasks: ufw.yml
