---
- name: Disable Proxmox Enterprise repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
    filename: /etc/apt/pbs-enterprise.list
    update_cache: true
  loop:
    - deb https://enterprise.proxmox.com/debian/pbs {{ ansible_distribution_release }} pve-enterprise

- name: Add Proxmox No Subscription repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: /etc/apt/sources
    update_cache: true
  loop:
    - deb http://download.proxmox.com/debian/pbs {{ ansible_distribution_release }}  pbs-no-subscription

- name: Remove Proxmox Text repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
    filename: /etc/apt/sources
    update_cache: true
  loop:
    - deb http://download.proxmox.com/debian/pbs {{ ansible_distribution_release }} pbstest
