---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: eraser
    namespace: eraser
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: eraser
            version: 1.3.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: eraser
                namespace: flux-system
