---
# Areas
- name: area/ansible
  color: "0e8a16"
- name: area/docker
  color: "72ccf3"
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/k8s
  color: "0e8a16"
- name: area/taskfile
  color: "0e8a16"
- name: area/terraform
  color: "0e8a16"
# Renovate Types
- name: renovate/ansible
  color: "027fa0"
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
- name: renovate/terraform
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Size
- name: size/XS
  color: "009900"
  description: >-
    Denotes a PR that changes 0-9 lines, ignoring generated files.
- name: size/S
  color: "77bb00"
  description: >-
    Denotes a PR that changes 10-29 lines, ignoring generated files.
- name: size/M
  color: "eebb00"
  description: >-
    Denotes a PR that changes 30-99 lines, ignoring generated files.
- name: size/L
  color: "ee9900"
  description: >-
    Denotes a PR that changes 100-499 lines, ignoring generated files.
- name: size/XL
  color: "ee5500"
  description: >-
    Denotes a PR that changes 500-999 lines, ignoring generated files.
- name: size/XXL
  color: "ee0000"
  description: >-
    Denotes a PR that changes 1000+ lines, ignoring generated files.
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: question
  color: "cc317c"
- name: doing-next
  color: "0E8A16"
- name: on-hold
  color: "B60205"
- name: needs-attention
  color: "B60205"
