# These settings are synced to GitHub by https://github.com/github/safe-settings
repository:
  license_template: mit
  description: This is my repository description
  homepage: https://www.irishlab.io
  
