---
# docker-compose exec mqtt mosquitto_passwd -c /mosquitto/conf/mosquitto.passwd mqtt
# mosquitto_passwd -c /mosquitto/config/password.txt mqtt
version: '3.8'

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
