---
name: pihole

networks:
  proxy:
    external: true

services:
  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:2024.07.0
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Toronto'
      WEBPASSWORD: ${password}
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pihole-prefix.addPrefix.prefix=/admin"
      - "traefik.http.middlewares.pihole.addprefix.prefix=/admin"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.middlewares=pihole-prefix"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.irishlab.io`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    networks:
      - proxy
