---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: core
    namespace: flux-system
spec:
    interval: 5m0s
    dependsOn:
        - name: helm
    path: ./k8s/cluster/homelab/core
    prune: true
    decryption:
        provider: sops
        secretRef:
            name: sops-age
    sourceRef:
        kind: GitRepository
        name: flux-system
