---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: helm
    namespace: flux-system
spec:
    interval: 5m0s
    path: ./k8s/cluster/homelab/helm
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
