---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: default
  labels:
    service: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
