---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: nvidia-feature-discovery
    namespace: invidia-gpu-discovery
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: gpu-feature-discovery
            version: 0.8.2
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: nvgfd
                namespace: flux-system
