---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: node-feature-discovery
    namespace: flux-system
spec:
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    interval: 10m
