---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: plex
    namespace: flux-system
spec:
    url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    interval: 10m
