---
- name: NUT | Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nut
    - nut-client
    - nut-server

- name: NUT | Servers Configuration file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - ups.conf
    - upsmon.conf
    - upsd.conf
    - nut.conf
    - upsd.users

- name: NUT | USB Configuration file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/udev/rules.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 99-nut-ups.rules
  notify: Reload nut

- name: Open NUT ports
  community.general.ufw:
    state: "{{ item.state }}"
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - name: NUT
      state: enabled
      rule: allow
      port: "3493"
      proto: tcp
  notify: Reload ufw
