---

- name: Packages | Debian Family
  block:
    - name: Packages | Update
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        cache_valid_time: 3600
        update_cache: true
        upgrade: dist
    - name: Packages | Kernel Update
      ansible.builtin.apt:
        upgrade: full
    - name: Packages | Remove leaf packages
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
  rescue:
    - name: APT Cache | Message
      ansible.builtin.debug:
        msg: "There was an error during the update cycle."
  always:
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: Rebooting to complete system upgrade
        reboot_timeout: 120
      when: reboot_required.stat.exists
