---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.16.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 10m
