---
name: tailscaled

# docker exec tailscaled tailscale up --hostname=rpi4-0 --advertise-exit-node  --accept-dns=true --advertise-routes=192.168.1.0/24,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,192.168.107.0/24

services:
  tailscaled:
    container_name: tailscaled
    image: docker.io/tailscale/tailscale:v1.76.6
    privileged: true
    network_mode: host
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTH_KEY=<secret>
      - TS_EXTRA_ARGS= --advertise-exit-node  --accept-dns=true --advertise-routes=192.168.1.0/24,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24,192.168.107.0/24
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
