---
name: gluetun

networks:
  vpn:
    name: vpn

services:

  vpn:
    container_name: vpn
    image: docker.io/qmcgaw/gluetun:v3.39.1
    cap_add:
      - NET_ADMIN
    networks:
      - vpn
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${username}
      - OPENVPN_PASSWORD=${password}
      - SERVER_REGIONS=Canada
      - SERVER_HOSTNAMES=ca1549.nordvpn.com
    restart: unless-stopped
