---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  releaseName: plex
  chart:
    spec:
    chart: plex/plex-media-server
    version: 0.2.1
    interval: 5m
    sourceRef:
      kind: HelmRepository
      name: plex
      namespace: flux-system
  interval: 10m
