---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: node-problem-detector
    namespace: node-problem-detector
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: deliveryhero
            version: 0.15.3
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: node-problem-detector
                namespace: flux-system
