---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: node-problem-detector
    namespace: node-problem-detector
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: node-problem-detector
            version: 2.3.12
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: deliveryhero
                namespace: flux-system
