---
- name: Packages | Install dependencies packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Repo | Add GPG signing key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/coral-edgetpu.asc
    mode: "0755"
    force: true
- name: Repo | Add coral repository
  ansible.builtin.apt_repository:
    filename: coral-edgetpu
    repo: deb https://packages.cloud.google.com/apt coral-edgetpu-stable main
    state: present
- name: Coral | Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - gasket-dkms
    - libedgetpu1-std
- name: Ensure the desired udev rules are in place
  ansible.builtin.blockinfile:
    path: /etc/udev/rules.d/65-apex.rules
    mode: 0644
    create: true
    block: |
      SUBSYSTEM==\"apex\", MODE=\"0660\", GROUP=\"apex\"
- name: Reload Udev
  ansible.builtin.command: |
          udevadm control --reload
  register: udev
  changed_when: udev.rc != 0
- name: User | Create apex group
  ansible.builtin.group:
    name: apex
    state: present
- name: User | Add user to apex group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: apex
