---
- name: Fail2Ban | Install package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    autoclean: true
  loop:
    - fail2ban

- name: Fail2Ban | jail.local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    mode: "0644"
    create: true
    block: |
      [sshd]
      enabled = true
      port    = 22
      maxretry = 5
      findtime  = 60m
      bantime  = 1w
      filter  = sshd
      ignoreip = 127.0.0.1/8 192.168.10.0/24 192.168.20.0/24 192.168.1.0/24
  notify: Restart fail2ban
