---
- name: Hardware | AMD GPU
  ansible.builtin.include_tasks: amd.yml
  when:
    - inventory_hostname not in groups["proxmox"]
    - gpu.amd.enabled is defined and gpu.amd.enabled

- name: Hardware | Intel GPU
  ansible.builtin.include_tasks: intel.yml
  when:
    - inventory_hostname not in groups["proxmox"]
    - gpu.intel.enabled is defined and gpu.intel.enabled

- name: Hardware | nVidia GPU
  ansible.builtin.include_tasks: nvidia.yml
  when:
    - inventory_hostname not in groups["proxmox"]
    - gpu.nvidia.enabled is defined and gpu.nvidia.enabled

- name: Hardware | Coral TPU
  ansible.builtin.include_tasks: coral.yml
  when:
    - inventory_hostname not in groups["proxmox"]
    - tpu.coral.enabled is defined and tpu.coral.enabled

# - name: Hardware | Nut Server
#   ansible.builtin.include_tasks: nut-server.yml
#   when:
#     - ups.server.enabled is defined and ups.server.enabled

# - name: Hardware | Nut Client
#   ansible.builtin.include_tasks: nut.yml
#   when:
#     - ups.client.enabled is defined and ups.client.enabled
#     - ansible_virtualization_role == "guest"
