---
- name: Packages | Remove snap packages
  community.general.snap:
    name: "{{ item }}"
    state: absent
  loop:
    - lxd
    - core18
    - core20
    - snapd
  when:
    - "'snapd' in ansible_facts.packages"
- name: Packages | Remove apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - snapd
- name: Packages | Remove snap files
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - /var/cache/snapd
    - /usr/lib/snapd
