---
- name: Packages | Install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - systemd-timesyncd
- name: Timezone | Install ntp package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    autoclean: true
  loop:
    - ntp
  notify: Start ntp
- name: Timezone | Locale
  community.general.timezone:
    name: "{{ system_timezone | default('Etc/UTC') }}"
