---
- name: Firewall | Ubuntu
  when:
    - ansible_os_family == "Debian"
  block:
    - name: Firewall | Install UFW packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
    # - name: Firewall | Set logging
    #   community.general.ufw:
    #     logging: "on"
    #   notify: Reload ufw
    - name: Firewall | Disable UFW service
      ansible.builtin.service:
        name: ufw
        state: stopped
