---
- name: Unattended-Upgrades | Install package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    autoclean: true
  loop:
    - unattended-upgrades

- name: Unattended-Upgrades | 2norecommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/2norecommends
    mode: "0644"
    create: true
    block: |
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";

- name: Unattended-Upgrades | 10periodic
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/10periodic
    mode: "0644"
    create: true
    block: |
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::Update-Package-Lists "1";

- name: Unattended-Upgrades | 50unattended-upgrades
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    create: true
    block: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
          "${distro_id}:${distro_codename}-updates";
          "${distro_id}:${distro_codename}";
          "${distro_id}ESM:${distro_codename}-infra-security";
          "${distro_id}ESMApps:${distro_codename}-apps-security";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:00";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

- name: Unattended-Upgrades | start systemd service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Unattended-Upgrades  restart systemd service
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted
