---
- name: User | Ensure groups are present
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
- name: User | Ensure sudo group has sudo privileges
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
- name: User | Give sudo access to {{ ansible_user }}
  ansible.builtin.blockinfile:
    path: /etc/sudoers
    insertafter: "%sudo ALL=(ALL:ALL) ALL"
    block: | # pragma: allowlist secret
      # Gives sudo access to the devops group
      {{ ansible_user }}        ALL=(ALL)       NOPASSWD: ALL
