# echo c > /proc/sysrq-trigger
---
# sudo nano /boot/firmware/config.txt
# # Enable watchdog monitoring
# dtparam=watchdog=on

- name: Watchdog | RPi4 Config
  when:
    - "'raspi' in ansible_kernel"
  block:
    - name: Watchdog | RPi4 Config
      ansible.builtin.debug:
        msg: sudo nano /boot/firmware/config.txt
    - name: Watchdog | RPi4 Config
      ansible.builtin.debug:
        msg: dtparam=watchdog=on

- name: Watchdog | Cloud Init Config
  when:
    - ansible_virtualization_role == "guest"
  block:
    - name: Watchdog | Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        autoclean: true
      loop:
        - linux-image-generic

- name: Watchdog | Debian Family
  when:
    - ansible_os_family == "Debian"
  block:
    - name: Watchdog | Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - watchdog
    - name: Watchdog | Enable watchdog module
      ansible.builtin.lineinfile:
        dest: /etc/default/watchdog
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        mode: "0644"
      with_items:
        - regexp: ^watchdog_module=
          line: watchdog_module="i6300esb"
      when:
        - ansible_virtualization_role == "guest"
    - name: Deploy | Watchdog configuration
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /etc/{{ item }}
        owner: root
        group: root
        mode: "0644"
      loop:
        - watchdog.conf
      notify: Start watchdog
