---
name: influxdb

volumes:
  influxdb:
    name: influxdb
    external: false

services:
  influxdb:
    container_name: influxdb
    image: docker.io/influxdb:2.1-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${username}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${password}
      - DOCKER_INFLUXDB_INIT_ORG=default
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    restart: unless-stopped
