---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  releaseName: kube-vip
  chart:
    spec:
      chart: kube-vip
      version: 0.6.4
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: ghcr.io/kube-vip/kube-vip
      tag: "v0.6.4"
    config:
      address: "192.168.10.250"
    env:
      vip_interface: ""
      vip_arp: "true"
      lb_enable: "true"
      lb_port: "6443"
      vip_cidr: "32"
      cp_enable: "true"
      svc_enable: "true"
      vip_leaderelection: "false"
