---
- name: Disable Proxmox Enterprise repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
    filename: /etc/apt/pve-enterprise.list
    update_cache: true
  loop:
    - deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise

- name: Add Proxmox No Subscription repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: /etc/apt/sources
    update_cache: true
  loop:
    - deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    - deb http://ftp.ca.debian.org/debian {{ ansible_distribution_release }} main contrib
    - deb http://ftp.ca.debian.org/debian {{ ansible_distribution_release }}-updates main contrib
    - deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security main contrib

- name: Remove Proxmox Text repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: absent
    filename: /etc/apt/sources
    update_cache: true
  loop:
    - deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pvetest
