---

- name: Update package manager
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  ansible.builtin.apt:
    autoremove: true
    update_cache: true
    upgrade: dist

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  notify: Reboot
