---

- name: Repo | Install dependencies packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg

- name: Ensure .gnupg config directory exists with right permissions
  ansible.builtin.file:
    dest: "{{ gpg_home }}/.gnupg"
    state: directory
    mode: "0700"
    owner: "{{ gpg_generator_user }}"

- name: Repo | Add GPG signing key
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /usr/share/keyrings/"{{ item.dest }}"
    mode: "0755"
    force: true
  with_items:
    - name: Github CLI
      url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      dest: githubcli-archive-keyring.gpg

- name: Repo | Add repository (amd64)
  ansible.builtin.apt_repository:
    filename: "{{ item.file }}"
    repo: "{{ item.repo }}"
    state: present
  with_items:
    - name: Tailscale
      file: tailscale
      repo: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/{{ tailscale_debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main
  when: ansible_facts.architecture == "x86_64"

- name: Repo | Install packages
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
- name: Packages | APT Install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gh
