---
- name: Download kind binary x64
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64
    checksum: sha256:https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64.sha256sum
    dest: /usr/local/bin/kind
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts.architecture == "x86_64"

- name: Download kind binary arm64
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-arm64
    checksum: sha256:https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-arm64.sha256sum
    dest: /usr/local/bin/kind
    owner: root
    group: root
    mode: "0755"
  when:
    - ( ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "64" ) or ansible_facts.architecture is search("aarch64")
