---
- name: NFS Share | Install nfs packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-common

- name: NFS Share | Unmount directory
  mount:
    path: "{{ item }}"
    state: unmounted
  loop:
    - /mnt/nas-1/backup
    - /mnt/nas-1/data
    - /mnt/nas-1/downloads
    - /mnt/nas-1/iso
    - /mnt/nas-1/media

- name: NFS Share | Create Folder
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /mnt/nas-1/backup
    - /mnt/nas-1/data
    - /mnt/nas-1/downloads
    - /mnt/nas-1/iso
    - /mnt/nas-1/media

# sudo ufw allow from client_ip to any port nfs

- name: NFS Share | Mount directory
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
    state: mounted
  with_items:
    - name: Flashy Iso
      src: nas-1.lan:/mnt/flashy/iso
      path: /mnt/nas-1/iso
    - name: Rusty Backup
      src: nas-1.lan://mnt/rusty/backup
      path: /mnt/nas-1/backup
    - name: Rusty Data
      src: nas-1.lan://mnt/rusty/data
      path: /mnt/nas-1/data
    - name: Rusty Downloads
      src: nas-1.lan://mnt/rusty/downloads
      path: /mnt/nas-1/downloads
    - name: Rusty Media
      src: nas-1.lan:/mnt/rusty/media
      path: /mnt/nas-1/media
