---
- name: Packages | Install workstation APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - flatpak
    - git
    - htop
    - neofetch
    - snapd
    - ubuntu-restricted-extras

- name: Packages | Install GUI APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnome-tweaks

- name: Packages | Install productivity APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - exa
    - make
    - virtualbox

- name: Packages | Install none productivity APT packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - vlc

- name: Packages | Install none productivity snap packages
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop:
    - discord

- name: Packages | Remove  snap packages
  community.general.snap:
    name: "{{ item }}"
    state: absent
  loop:
    - firefox
