---
- name: Python | Install python packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - pipx
    - python3
    - python3-pip
    - python3-venv

- name: Python | Pipx install packages
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - poetry
    - pre-commit
    - pytest
