---
- name: Repo | Install dependencies packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - curl
    - gnupg-agent
    - gnupg2
    - python3-apt

- name: Repo | Add GPG signing key
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: /usr/share/keyrings/"{{ item.dest }}"
    mode: "0755"
    force: true
  with_items:
    - name: Tailscale
      url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
      dest: tailscale-archive-keyring.gpg

- name: Repo | Add repository (amd64)
  ansible.builtin.apt_repository:
    filename: "{{ item.file }}"
    repo: "{{ item.repo }}"
    state: present
  with_items:
    - name: Tailscale
      file: tailscale
      repo: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main
  when: ansible_facts.architecture == "x86_64"

- name: Repo | Install packages
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
- name: Packages | APT Install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - tailscale
