---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: node-problem-detector
    namespace: flux-system
spec:
    url: https://charts.deliveryhero.io/
    interval: 10m
