---
- name: Reboot
  ansible.builtin.reboot:
    msg: Rebooting nodes
    reboot_timeout: 3600
    test_command: uptime
  when:
    - reboot_required_file.stat.exists

- name: Reboot force
  ansible.builtin.reboot:
    msg: Rebooting nodes
    reboot_timeout: 3600
    test_command: uptime

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Update GRUB
  ansible.builtin.command: >
    update-grub
  register: grub
  changed_when: grub.rc != 0

- name: Refresh initramfs
  ansible.builtin.command: >
    update-initramfs -u -k all
  register: initramfs
  changed_when: initramfs.rc != 0

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted
