---
name: whoami

networks:
  proxy:
    external: true

services:
  whoami:
    container_name: whoami
    image: docker.io/traefik/whoami:v1.10
    pull_policy: always
    restart: unless-stopped
    command:
      - --name=internal
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.internal.entrypoints=https"
      - "traefik.http.routers.internal.rule=Host(`internal.local.irishlab.io`)"
      - "traefik.http.routers.internal.service=internal"
      - "traefik.http.routers.internal.tls=true"

      - "traefik.http.services.internal.loadbalancer.server.port=80"
    networks:
      - proxy
