---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
  interval: 10m
  values:
