---
version: '3.8'

volumes:
  prometheus_data:
    name: prometheus_data
    external: false

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
