---
version: '3.4'

volumes:
  prowlarr:
    name: prowlarr
    external: false

services:
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:1.15.0
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - 'prowlarr:/config'
    restart: unless-stopped
