---
version: "3"

services:
  watchtower:
    container_name: watchtower
    image: ghcr.io/containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
