---
volumes:
  tautulli:
    name: tautulli
    external: false

services:
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:2.14.2
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - tautulli:/config
    restart: unless-stopped
