---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 10m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
