---
name: portainer

volumes:
  portainer:
    name: portainer
    external: false

services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.24.0
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
