---

version: "3"

volumes:
  portainer:
    name: portainer
    external: false

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
