---
name: ansible-semaphore
volumes:
  ansible-semaphore-config:
    name: ansible-semaphore-config
    external: false
  ansible-semaphore-db:
    name: ansible-semaphore-db
    external: false

services:
  ansible-semaphore:
    image: docker.io/semaphoreui/semaphore:v2.9.64
    pull_policy: always
    container_name: ansible-semaphore
    restart: always
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3000
        published: "3010"
        protocol: tcp
    environment:
      SEMAPHORE_ADMIN_EMAIL: ${email}
      SEMAPHORE_ADMIN_NAME: ${username}
      SEMAPHORE_ADMIN_PASSWORD: ${password}
      SEMAPHORE_ADMIN: ${username}
      SEMAPHORE_DB_DIALECT: bolt
    volumes:
      - ansible-semaphore-config:/etc/semaphore
      - ansible-semaphore-db:/var/lib/semaphore
