---
mqtt:
  host: ${host}
  port: ${port}
  user: ${username}
  password: ${password}
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: pci

detect:
  fps: 5
  enabled: true
  max_disappeared: 25

live:
  height: 640
  quality: 1

record:
  enabled: false
  expire_interval: 60
  retain:
    days: 0
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 10

snapshots:
  enabled: false
  timestamp: true
  bounding_box: true
  retain:
    default: 10

ui:
  use_experimental: false
  live_mode: mse

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://${username}:${password}${host}:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://${username}:${password}@${host}:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      track:
        - bicycle
        - bird
        - bus
        - car
        - cat
        - dog
        - motorcycle
        - person
      filters:
        cat:
          min_score: 0.3
          threshold: 0.5
        dog:
          min_score: 0.3
          threshold: 0.5
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
