---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: podinfo
    namespace: default
spec:
    interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    chart:
        spec:
            chart: podinfo
            version: 6.6.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: podinfo
                namespace: flux-system
    values:
        replicaCount: 3
        backend: http://backend-podinfo:9898/echo

        resources:
            limits:
                memory: 256Mi
            requests:
                cpu: 100m
                memory: 64Mi
        hpa:
            enabled: true
            maxReplicas: 10
            cpu: 50m
            memory: 32Mi
            requests:
