---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: plex
    namespace: plex
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: plex/plex-media-server
            version: 0.2.1
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: plex
                namespace: flux-system
