---
# kind create cluster --name fluxcd --image kindest/node:v1.29.2
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3d-cluster
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.27.8+k3s1
