---

- name: Create manifests directory on first k3s_control
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_control'][0]]['ansible_hostname']

- name: Download kube-vip rbac manifest to first k3s_control
  ansible.builtin.get_url:
    url: "https://kube-vip.io/manifests/rbac.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_control'][0]]['ansible_hostname']

- name: Copy kube-vip manifest to first k3s_control
  template:
    src: "kube-vip.yml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['k3s_control'][0]]['ansible_hostname']
