---

- name: Configure for Intel CPU
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items:
    - regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet {{ detected_cpu }}_iommu=on i915.enable_gvt=1"'
  notify: Update GRUB

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: Test for dmesg
  ansible.builtin.debug:
    msg: "dmesg | grep -e DMAR -e IOMMU"

- name: Configure Modules
  ansible.builtin.blockinfile:
    path: /etc/modules
    mode: 0644
    create: true
    block: |
      # Modules required for PCI passthrough
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd

      # Modules required for Intel GVT
      kvmgt
      exngt
      vfio-mdev
  notify: Reboot force

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers

- name: Configure ModProbe Blacklist
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/modprobe.d/blacklist.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items:
    - regexp: "^blacklist i915"
      line: "blacklist i915"
