---
- name: Packages | Install Cloud Init packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - cron
    - libguestfs-tools
    - wget
  run_once: true

- name: Packages | Install SDN packages
  ansible.builtin.include_tasks: sdn.yml
