---
version: '3.4'

volumes:
  radarr:
    name: radarr
    external: false
  downloads:
    name: downloads
    driver_opts:
      type: nfs
      o: addr=nas-1.lan,nolock,soft,rw
      device: :/mnt/rusty/downloads/
  movies:
    name: movies
    driver_opts:
      type: nfs
      o: addr=nas-1.lan,nolock,soft,rw
      device: :/mnt/rusty/media/movies

services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.3.6
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - 'radarr:/config'
      - 'movies:/movies'
      - 'downloads:/downloads'
    restart: unless-stopped
