---
name: cloudflared

networks:
  cloud:
    external: true

services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:2024.11.1
    command: tunnel run --token ${api_token}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cloud
