---
name: cloudflared

networks:
  cloudflared:
    driver: bridge
    name: cloudflared

services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: docker.io/cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${api_token}
    restart: unless-stopped
