---
profile: basic
exclude_paths:
  - .cache/
  - .github/
  - .vscode/
  - .taskfiles/
  - docker/
  - infra/
  - k8s/
  - terraform/
warn_list:
  - yaml[line-length]
# skip_list:
#  - yaml[line-length]
task_name_prefix: "{stem} | "
