---
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: apps
  labels:
    service: whoami
spec:
  selector:
    app: whoami
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
