---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: stakater
    namespace: reloader
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: reloader
            version: 1.0.74
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: flux-system
