---

- name: Docker | Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apparmor-utils
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin

- name: Docker | Clean Up
  block:
    - name: Docker | Prune dangling image
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false
  rescue:
    - name: Docker | Docker API not found
      ansible.builtin.debug:
        msg: "Docker API not found, maybe it is not installed"
