---
- name: Setup proxmox-pbs host
  hosts:
    - pbs
  become: true
  gather_facts: true
  any_errors_fatal: false
  pre_tasks:
    - name: Ping machine
      ansible.builtin.ping:

    - name: Show the uptime
      ansible.builtin.debug:
        msg: Uptime {{ now().replace(microsecond=0) - now().fromtimestamp(now(fmt='%s') | int - ansible_uptime_seconds) }}

    - name: Disable Proxmox Enterprise repository
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: absent
        filename: /etc/apt/pbs-enterprise.list
      loop:
        - deb https://enterprise.proxmox.com/debian/pbs {{ ansible_distribution_release }} pbs-enterprise

    - name: Add Proxmox No Subscription repository
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: /etc/apt/sources
      loop:
        - deb http://download.proxmox.com/debian/pbs {{ ansible_distribution_release }}  pbs-no-subscription

    - name: Remove Proxmox Text repository
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: absent
        filename: /etc/apt/sources
      loop:
        - deb http://download.proxmox.com/debian/pbs {{ ansible_distribution_release }} pbstest
  roles:
    - role: common_setup
    - role: proxmox_pbs
  post_tasks:
    - name: Status message
      ansible.builtin.debug:
        msg: Playbook ran without any issue.
