---
name: gotify

networks:
  proxy:
    external: true

services:
  gotify:
    image: gotify/server:2.6.1
    container_name: gotify
    pull_policy: always
    restart: unless-stopped
    # environment:
    #   - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - './gotify_data:/app/data'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=https"
      - "traefik.http.routers.gotify.rule=Host(`gotify.local.irishlab.io`)"
      - "traefik.http.routers.gotify.tls=true"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    networks:
      - proxy
