---
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v0.8.10
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
