---
version: '3'
name: nginx
volumes:
  nginx-data:
    name: nginx-data
    driver: local
services:
  nginx:
    image: nginx:1.24.0-alpine
    pull_policy: always
    container_name: nginx
    restart: always
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "8080"
        protocol: tcp
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
networks:
  default:
    name: nginx_default
