---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: intel-device-plugins-operator
    namespace: intel-device-plugins-operator
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: intel-device-plugins-operator
            version: 0.29.0
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: intel
                namespace: flux-system
