---
- name: Create manifests directory on first control
  file:
    path: /tmp/k3s/
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Create the storage directory if it does not exist
  ansible.builtin.file:
    path: "{{ longhorn_storage_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Add longhorn repository to the controller
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "{{ longhorn_helm_repourl }}"

- name: Install longhorn via helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    set_values:
      - value: service.ui.loadBalancerIP="{{ longhorn_loadbalancer_ip }}"
        value_type: string
      - value: service.ui.type=LoadBalancer
        value_type: string
      - value: defaultSettings.defaultDataPath="{{ longhorn_storage_dir }}"
        value_type: string

- name: Download longhorn manifest to first control
  ansible.builtin.get_url:
    url: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_tag_version }}/deploy/longhorn.yaml
    dest: /var/lib/rancher/k3s/server/manifests/longhorn.yaml
    owner: root
    group: root
    mode: "0644"

- name: Test longhorn daemonsets configuration
  command: >-
    k3s kubectl -n {{ item.namespace }} get {{ item.resource }}
  changed_when: false
  with_items:
    - namespace: longhorn-system
      resource: deployment/longhorn-ui
