---

- name: Deploy default manifest
  include_tasks: "{{ item }}"
  loop:
    - metallb.yml
    - kured.yml
    - system-upgrade.yml
    # - longhorn.yml
  run_once: true
  when: ansible_hostname == hostvars[groups['k3s_control'][0]]['ansible_hostname']

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent

- name: Get k3s config file
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_base64
  run_once: true
  when: ansible_hostname == hostvars[groups['k3s_control'][0]]['ansible_hostname']

# - name: Write Kubernetes config file with the correct cluster address
#   ansible.builtin.copy:
#     content: "{{ kubeconfig_base64.content | b64decode | replace('127.0.0.1', apiserver_endpoint ) }}"
#     dest: "~/.kube/config"
#     mode: 0600
#   delegate_to: localhost
#   run_once: true
# - name: kubeconfig | update kubeconfig with the right IPv4 address
#   delegate_to: localhost
#   become: false
#   run_once: true
#   ansible.builtin.replace:
#     path: "/tmp/kubeconfig"
#     regexp: 'https://127.0.0.1:6443'
#     replace: 'https://{{ k3s_registration_domain }}:6443'
