---

- name: Create manifests directory on first control
  file:
    path: /tmp/k3s/
    state: directory
    owner: root
    group: root
    mode: 0644

# sudo touch /var/run/reboot-required for testing purpose
- name: Download kured manifest to first control
  ansible.builtin.get_url:
    url: "https://github.com/kubereboot/kured/releases/download/1.14.1/kured-1.14.1-dockerhub.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/kured.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['control'][0]]['ansible_hostname']
