---
version: "3"
name: ansible-semaphore
volumes:
  ansible-semaphore-config:
    name: ansible-semaphore-config
    external: false
  ansible-semaphore-db:
    name: ansible-semaphore-db
    external: false

services:
  ansible-semaphore:
    image: semaphoreui/semaphore:v2.9.37
    pull_policy: always
    container_name: ansible-semaphore
    restart: always
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    environment:
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_DB_DIALECT: bolt
    volumes:
      - ansible-semaphore-config:/etc/semaphore
      - ansible-semaphore-db:/var/lib/semaphore
    # healthcheck:
    #   test: curl --fail http://localhost || exit 1
    #   interval: 60s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
networks:
  default:
    name: ansible-semaphore_default
