---
name: whoami

networks:
  proxy:
    external: true

services:
  whoami:
    image: docker.io/traefik/whoami:v1.10
    pull_policy: always
    container_name: whoami
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local.irishlab.io`)"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - proxy
