---
name: whoami
services:
  whoami:
    image: docker.io/traefik/whoami:v1.10
    pull_policy: always
    container_name: nginx
    restart: unless-stopped
    # networks:
    #   - frontend
    #   - backend
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 64M
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami-http.entrypoints: "web"
      traefik.http.routers.whoami-http.rule: "Host(`whoami.home.irishlab.io`)"
      traefik.http.routers.whoami-https.entrypoints: "websecure"
      traefik.http.routers.whoami-https.rule: "Host(`whoami.home.irishlab.io`)"
      traefik.http.routers.whoami-https.tls: "true"
      traefik.http.routers.whoami-https.tls.certresolver: "cloudflare"
