---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: kube-system
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    defaultSettings:
      backupTarget: nfs://192.168.30.11/backup
    longhornUI:
      replicas: 1
    service:
      ui:
        type: LoadBalancer
