---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-nfs-pv
  namespace: default
  labels:
    app: nginx
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
