---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: eraser
    namespace: flux-system
spec:
    url: https://eraser-dev.github.io/eraser/charts
    interval: 10m
