---
name: Run Ansible-Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
