---
name: Continous Deployment

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:

  runner-tf:
    uses: ./.github/workflows/runner-tf.yml

  runner-dns:
    uses: ./.github/workflows/runner-dns.yml

  runner-ansible:
    uses: ./.github/workflows/runner-ansible.yml
