---
name: Continous Deployment

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:

  hello-world:
    name: Call Hello World
    uses: irishlab-io/admin/.github/workflows/reusable-hello-world.yml@main

    with:
      comments: "4321tset"
      enable: false
