---
name: Run linting

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: '-c .config/.yamllint.yml ./k8s/'
