---
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5

    steps:

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          configuration-path: .github/labeler.yml
