---
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1.9.3
        id: generate-token
        with:
          app-id: "${{ secrets.IRISHLAB_BOT_APP_ID }}"
          private-key: "${{ secrets.IRISHLAB_BOT_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ steps.generate-token.outputs.token }}"
