---
name: Meta - Sync labels

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Generate Token
        uses: actions/create-github-app-token@v1.10.0
        id: generate-token
        with:
          app-id: "${{ secrets.IRISHLAB_BOT_APP_ID }}"
          private-key: "${{ secrets.IRISHLAB_BOT_PRIVATE_KEY }}"

      - name: Sync Labels
        uses: EndBug/label-sync@v2.3.3
        with:
          config-file: .github/labels.yml
          token: "${{ steps.generate-token.outputs.token }}"
          delete-other-labels: true
