---
name: Continous Integration - Pull Requst

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  secret:
    name: Call Secret Scanning
    uses: irishlab-io/admin/.github/workflows/reusable-secret.yml@main
    secrets: inherit

  ansible-lint:
    name: Call Ansible-Lint
    uses: irishlab-io/admin/.github/workflows/reusable-ansible-lint.yml@main

    needs:
      - secret

    with:
      configuration_file: "-c ./.config/.ansible-lint.yml"
      requirements_file: "./ansible/collections/requirements.yml"
