---
name: Runner for DNS

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  cd-local-dns:
    name: Runner - DNS Local
    runs-on: self-hosted
    # runs-on: "self-hosted"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

  cd-tf-dns:
    name: Runner - DNS Terraform
    runs-on: ubuntu-24.04
    # environment: production
    timeout-minutes: 5

    env:
      working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: $

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
