---
name: Runner - Ansible Inventory

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Ansible Runner
    runs-on: "self-hosted"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SCP files via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_USER }}
          source: './ansible/inventory/*'
          target: '~/ansible/inventory/'
          strip_components: 2
