---
name: Runner - Ansible Inventory

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - 'ansible/inventory/*'

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ${username}
          host: ${host}
          key: ${{ secrets.SSH_USER }}
          source: './ansible/inventory/*'
          target: '~/ansible/inventory/'
          strip_components: 2
