---
name: Runner for Terraform

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  cd-tf:
    name: Runner - Terraform
    runs-on: ubuntu-latest
    # runs-on: "self-hosted"
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
