---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: chaos-mesh
    namespace: chaos-mesh
spec:
    interval: 5m
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    chart:
        spec:
            chart: chaos-mesh
            version: 2.6.3
            interval: 5m
            sourceRef:
                kind: HelmRepository
                name: chaos-mesh
                namespace: flux-system
    values:
        chaosDaemon:
            runtime: "containerd"
            socketPath: "/run/containerd/containerd.sock"
