---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: demo
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: docker.io/traefik/whoami:v1.10.3
          ports:
            - name: whoami
              containerPort: 80
